// <auto-generated />
namespace Books.Web.DataContext.BookMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class librarySchema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(librarySchema));
        
        string IMigrationMetadata.Id
        {
            get { return "201702042003061_librarySchema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
